#include "FunctionCodes.h"

const char* FLR_FUNCTION_c_str(FLR_FUNCTION f) {
    switch (f) {
            // Module gao
        case GAO_SETGAINSTATE:
            return "GAO_SETGAINSTATE";
        case GAO_GETGAINSTATE:
            return "GAO_GETGAINSTATE";
        case GAO_SETFFCSTATE:
            return "GAO_SETFFCSTATE";
        case GAO_GETFFCSTATE:
            return "GAO_GETFFCSTATE";
        case GAO_SETTEMPCORRECTIONSTATE:
            return "GAO_SETTEMPCORRECTIONSTATE";
        case GAO_GETTEMPCORRECTIONSTATE:
            return "GAO_GETTEMPCORRECTIONSTATE";
        case GAO_SETICONSTL:
            return "GAO_SETICONSTL";
        case GAO_GETICONSTL:
            return "GAO_GETICONSTL";
        case GAO_SETICONSTM:
            return "GAO_SETICONSTM";
        case GAO_GETICONSTM:
            return "GAO_GETICONSTM";
        case GAO_SETAVERAGERSTATE:
            return "GAO_SETAVERAGERSTATE";
        case GAO_GETAVERAGERSTATE:
            return "GAO_GETAVERAGERSTATE";
        case GAO_SETNUMFFCFRAMES:
            return "GAO_SETNUMFFCFRAMES";
        case GAO_GETNUMFFCFRAMES:
            return "GAO_GETNUMFFCFRAMES";
        case GAO_GETAVERAGERTHRESHOLD:
            return "GAO_GETAVERAGERTHRESHOLD";
        case GAO_SETRNSSTATE:
            return "GAO_SETRNSSTATE";
        case GAO_GETRNSSTATE:
            return "GAO_GETRNSSTATE";
        case GAO_SETTESTRAMPSTATE:
            return "GAO_SETTESTRAMPSTATE";
        case GAO_GETTESTRAMPSTATE:
            return "GAO_GETTESTRAMPSTATE";
        case GAO_SETSFFCSTATE:
            return "GAO_SETSFFCSTATE";
        case GAO_GETSFFCSTATE:
            return "GAO_GETSFFCSTATE";
        case GAO_SETNUCTYPE:
            return "GAO_SETNUCTYPE";
        case GAO_GETNUCTYPE:
            return "GAO_GETNUCTYPE";
        case GAO_SETFFCZEROMEANSTATE:
            return "GAO_SETFFCZEROMEANSTATE";
        case GAO_GETFFCZEROMEANSTATE:
            return "GAO_GETFFCZEROMEANSTATE";
        case GAO_SETCOMBINEMEANSENABLESTATE:
            return "GAO_SETCOMBINEMEANSENABLESTATE";
        case GAO_GETCOMBINEMEANSENABLESTATE:
            return "GAO_GETCOMBINEMEANSENABLESTATE";
        case GAO_SETRNSPOPTHRESHOLD:
            return "GAO_SETRNSPOPTHRESHOLD";
        case GAO_GETRNSPOPTHRESHOLD:
            return "GAO_GETRNSPOPTHRESHOLD";
        case GAO_SETRNSCLOSETHRESHOLD:
            return "GAO_SETRNSCLOSETHRESHOLD";
        case GAO_GETRNSCLOSETHRESHOLD:
            return "GAO_GETRNSCLOSETHRESHOLD";
        case GAO_SETRNSTOOFEWQUIT:
            return "GAO_SETRNSTOOFEWQUIT";
        case GAO_GETRNSTOOFEWQUIT:
            return "GAO_GETRNSTOOFEWQUIT";
        case GAO_SETRNSTOOFEW:
            return "GAO_SETRNSTOOFEW";
        case GAO_GETRNSTOOFEW:
            return "GAO_GETRNSTOOFEW";
        case GAO_SETRNSMINCORRECTION:
            return "GAO_SETRNSMINCORRECTION";
        case GAO_GETRNSMINCORRECTION:
            return "GAO_GETRNSMINCORRECTION";
        case GAO_SETRNSDAMPING:
            return "GAO_SETRNSDAMPING";
        case GAO_GETRNSDAMPING:
            return "GAO_GETRNSDAMPING";
        case GAO_SETRNSFRAMEHYSTERESIS:
            return "GAO_SETRNSFRAMEHYSTERESIS";
        case GAO_GETRNSFRAMEHYSTERESIS:
            return "GAO_GETRNSFRAMEHYSTERESIS";
        case GAO_SETRNSBADDAMPING:
            return "GAO_SETRNSBADDAMPING";
        case GAO_GETRNSBADDAMPING:
            return "GAO_GETRNSBADDAMPING";
        case GAO_SETRNSNUMGOODDAMPINGTHRESHOLD:
            return "GAO_SETRNSNUMGOODDAMPINGTHRESHOLD";
        case GAO_GETRNSNUMGOODDAMPINGTHRESHOLD:
            return "GAO_GETRNSNUMGOODDAMPINGTHRESHOLD";
        case GAO_GETRNSFFCDESIRED:
            return "GAO_GETRNSFFCDESIRED";
        case GAO_GETAVERAGERDESIREDSTATE:
            return "GAO_GETAVERAGERDESIREDSTATE";
        case ROIC_GETFPATEMP:
            return "ROIC_GETFPATEMP";
        case ROIC_GETFRAMECOUNT:
            return "ROIC_GETFRAMECOUNT";
        case ROIC_GETACTIVENORMALIZATIONTARGET:
            return "ROIC_GETACTIVENORMALIZATIONTARGET";
        case ROIC_SETFPARAMPSTATE:
            return "ROIC_SETFPARAMPSTATE";
        case ROIC_GETFPARAMPSTATE:
            return "ROIC_GETFPARAMPSTATE";
        case ROIC_GETSENSORADC1:
            return "ROIC_GETSENSORADC1";
        case ROIC_GETSENSORADC2:
            return "ROIC_GETSENSORADC2";
        case ROIC_SETFPATEMPOFFSET:
            return "ROIC_SETFPATEMPOFFSET";
        case ROIC_GETFPATEMPOFFSET:
            return "ROIC_GETFPATEMPOFFSET";
        case ROIC_SETFPATEMPMODE:
            return "ROIC_SETFPATEMPMODE";
        case ROIC_GETFPATEMPMODE:
            return "ROIC_GETFPATEMPMODE";
        case ROIC_GETFPATEMPTABLE:
            return "ROIC_GETFPATEMPTABLE";
        case ROIC_SETFPATEMPVALUE:
            return "ROIC_SETFPATEMPVALUE";
        case ROIC_GETFPATEMPVALUE:
            return "ROIC_GETFPATEMPVALUE";
        case ROIC_GETPREAMBLEERROR:
            return "ROIC_GETPREAMBLEERROR";
        case ROIC_INDUCEPREAMBLEERROR:
            return "ROIC_INDUCEPREAMBLEERROR";
        case ROIC_GETROICSTARTED:
            return "ROIC_GETROICSTARTED";
        case BPR_GETSTATE:
            return "BPR_GETSTATE";
        case BPR_SETSTATE:
            return "BPR_SETSTATE";
        case BPR_GETSTATS:
            return "BPR_GETSTATS";
        case BPR_GETDISPLAYMODE:
            return "BPR_GETDISPLAYMODE";
        case BPR_SETDISPLAYMODE:
            return "BPR_SETDISPLAYMODE";
        case BPR_GETDISPLAYMODEMINVALUE:
            return "BPR_GETDISPLAYMODEMINVALUE";
        case BPR_SETDISPLAYMODEMINVALUE:
            return "BPR_SETDISPLAYMODEMINVALUE";
        case BPR_GETDISPLAYMODEMAXVALUE:
            return "BPR_GETDISPLAYMODEMAXVALUE";
        case BPR_SETDISPLAYMODEMAXVALUE:
            return "BPR_SETDISPLAYMODEMAXVALUE";
        case BPR_GETWORKBUFINDEX:
            return "BPR_GETWORKBUFINDEX";
        case BPR_SETWORKBUFINDEX:
            return "BPR_SETWORKBUFINDEX";
        case BPR_GETWORKBUFSTATS:
            return "BPR_GETWORKBUFSTATS";
        case TELEMETRY_SETSTATE:
            return "TELEMETRY_SETSTATE";
        case TELEMETRY_GETSTATE:
            return "TELEMETRY_GETSTATE";
        case TELEMETRY_SETLOCATION:
            return "TELEMETRY_SETLOCATION";
        case TELEMETRY_GETLOCATION:
            return "TELEMETRY_GETLOCATION";
        case TELEMETRY_SETPACKING:
            return "TELEMETRY_SETPACKING";
        case TELEMETRY_GETPACKING:
            return "TELEMETRY_GETPACKING";
        case BOSON_GETCAMERASN:
            return "BOSON_GETCAMERASN";
        case BOSON_GETCAMERAPN:
            return "BOSON_GETCAMERAPN";
        case BOSON_GETSENSORSN:
            return "BOSON_GETSENSORSN";
        case BOSON_RUNFFC:
            return "BOSON_RUNFFC";
        case BOSON_SETFFCTEMPTHRESHOLD:
            return "BOSON_SETFFCTEMPTHRESHOLD";
        case BOSON_GETFFCTEMPTHRESHOLD:
            return "BOSON_GETFFCTEMPTHRESHOLD";
        case BOSON_SETFFCFRAMETHRESHOLD:
            return "BOSON_SETFFCFRAMETHRESHOLD";
        case BOSON_GETFFCFRAMETHRESHOLD:
            return "BOSON_GETFFCFRAMETHRESHOLD";
        case BOSON_GETFFCINPROGRESS:
            return "BOSON_GETFFCINPROGRESS";
        case BOSON_REBOOT:
            return "BOSON_REBOOT";
        case BOSON_SETFFCMODE:
            return "BOSON_SETFFCMODE";
        case BOSON_GETFFCMODE:
            return "BOSON_GETFFCMODE";
        case BOSON_SETGAINMODE:
            return "BOSON_SETGAINMODE";
        case BOSON_GETGAINMODE:
            return "BOSON_GETGAINMODE";
        case BOSON_WRITEDYNAMICHEADERTOFLASH:
            return "BOSON_WRITEDYNAMICHEADERTOFLASH";
        case BOSON_READDYNAMICHEADERFROMFLASH:
            return "BOSON_READDYNAMICHEADERFROMFLASH";
        case BOSON_RESTOREFACTORYDEFAULTSFROMFLASH:
            return "BOSON_RESTOREFACTORYDEFAULTSFROMFLASH";
        case BOSON_RESTOREFACTORYBADPIXELSFROMFLASH:
            return "BOSON_RESTOREFACTORYBADPIXELSFROMFLASH";
        case BOSON_WRITEBADPIXELSTOFLASH:
            return "BOSON_WRITEBADPIXELSTOFLASH";
        case BOSON_GETSOFTWAREREV:
            return "BOSON_GETSOFTWAREREV";
        case BOSON_SETBADPIXELLOCATION:
            return "BOSON_SETBADPIXELLOCATION";
            return "BOSON_LOOKUPFPATEMPDEGKX";
        case BOSON_WRITELENSNVFFCTOFLASH:
            return "BOSON_WRITELENSNVFFCTOFLASH";
        case BOSON_WRITELENSGAINTOFLASH:
            return "BOSON_WRITELENSGAINTOFLASH";
        case BOSON_SETLENSNUMBER:
            return "BOSON_SETLENSNUMBER";
        case BOSON_GETLENSNUMBER:
            return "BOSON_GETLENSNUMBER";
        case BOSON_SETTABLENUMBER:
            return "BOSON_SETTABLENUMBER";
        case BOSON_GETTABLENUMBER:
            return "BOSON_GETTABLENUMBER";
        case BOSON_GETSENSORPN:
            return "BOSON_GETSENSORPN";
        case BOSON_SETGAINSWITCHPARAMS:
            return "BOSON_SETGAINSWITCHPARAMS";
        case BOSON_GETGAINSWITCHPARAMS:
            return "BOSON_GETGAINSWITCHPARAMS";
        case BOSON_GETSWITCHTOHIGHGAINFLAG:
            return "BOSON_GETSWITCHTOHIGHGAINFLAG";
        case BOSON_GETSWITCHTOLOWGAINFLAG:
            return "BOSON_GETSWITCHTOLOWGAINFLAG";
        case BOSON_GETCLOWTOHIGHPERCENT:
            return "BOSON_GETCLOWTOHIGHPERCENT";
        case BOSON_GETMAXNUCTABLES:
            return "BOSON_GETMAXNUCTABLES";
        case BOSON_GETMAXLENSTABLES:
            return "BOSON_GETMAXLENSTABLES";
        case BOSON_GETFFCWAITCLOSEFRAMES:
            return "BOSON_GETFFCWAITCLOSEFRAMES";
        case BOSON_SETFFCWAITCLOSEFRAMES:
            return "BOSON_SETFFCWAITCLOSEFRAMES";
        case BOSON_CHECKFORTABLESWITCH:
            return "BOSON_CHECKFORTABLESWITCH";
        case BOSON_GETDESIREDTABLENUMBER:
            return "BOSON_GETDESIREDTABLENUMBER";
        case BOSON_GETFFCSTATUS:
            return "BOSON_GETFFCSTATUS";
        case BOSON_GETFFCDESIRED:
            return "BOSON_GETFFCDESIRED";
        case BOSON_GETSWREVINHEADER:
            return "BOSON_GETSWREVINHEADER";
        case BOSON_GETLASTFFCFRAMECOUNT:
            return "BOSON_GETLASTFFCFRAMECOUNT";
        case BOSON_GETTABLESWITCHDESIRED:
            return "BOSON_GETTABLESWITCHDESIRED";
        case BOSON_GETOVERTEMPTHRESHOLD:
            return "BOSON_GETOVERTEMPTHRESHOLD";
        case BOSON_GETLOWPOWERMODE:
            return "BOSON_GETLOWPOWERMODE";
        case BOSON_GETOVERTEMPEVENTOCCURRED:
            return "BOSON_GETOVERTEMPEVENTOCCURRED";
        case BOSON_SETPERMITTHERMALSHUTDOWNOVERRIDE:
            return "BOSON_SETPERMITTHERMALSHUTDOWNOVERRIDE";
        case BOSON_GETPERMITTHERMALSHUTDOWNOVERRIDE:
            return "BOSON_GETPERMITTHERMALSHUTDOWNOVERRIDE";
        case BOSON_GETMYRIADTEMP:
            return "BOSON_GETMYRIADTEMP";
            return "BOSON_GETFFCWARNTIMEINSECX";
        case BOSON_GETOVERTEMPEVENTCOUNTER:
            return "BOSON_GETOVERTEMPEVENTCOUNTER";
        case BOSON_SETOVERTEMPTIMERINSEC:
            return "BOSON_SETOVERTEMPTIMERINSEC";
        case BOSON_GETOVERTEMPTIMERINSEC:
            return "BOSON_GETOVERTEMPTIMERINSEC";
        case BOSON_UNLOADCURRENTLENSCORRECTIONS:
            return "BOSON_UNLOADCURRENTLENSCORRECTIONS";
        case BOSON_SETTIMEFORQUICKFFCSINSECS:
            return "BOSON_SETTIMEFORQUICKFFCSINSECS";
        case BOSON_GETTIMEFORQUICKFFCSINSECS:
            return "BOSON_GETTIMEFORQUICKFFCSINSECS";
        case BOSON_RELOADCURRENTLENSCORRECTIONS:
            return "BOSON_RELOADCURRENTLENSCORRECTIONS";
        case BOSON_GETBOOTTIMESTAMPS:
            return "BOSON_GETBOOTTIMESTAMPS";
        case BOSON_SETEXTSYNCMODE:
            return "BOSON_SETEXTSYNCMODE";
        case BOSON_GETEXTSYNCMODE:
            return "BOSON_GETEXTSYNCMODE";
        case BOSON_GETLASTCOMMAND:
            return "BOSON_GETLASTCOMMAND";
        case BOSON_GETSENSORHOSTCALVERSION:
            return "BOSON_GETSENSORHOSTCALVERSION";
        case BOSON_SETDESIREDSTARTUPTABLENUMBER:
            return "BOSON_SETDESIREDSTARTUPTABLENUMBER";
        case BOSON_GETDESIREDSTARTUPTABLENUMBER:
            return "BOSON_GETDESIREDSTARTUPTABLENUMBER";
        case BOSON_SETINVERTIMAGE:
            return "BOSON_SETINVERTIMAGE";
        case BOSON_GETINVERTIMAGE:
            return "BOSON_GETINVERTIMAGE";
        case BOSON_SETREVERTIMAGE:
            return "BOSON_SETREVERTIMAGE";
        case BOSON_GETREVERTIMAGE:
            return "BOSON_GETREVERTIMAGE";
        case BOSON_GETTIMESTAMP:
            return "BOSON_GETTIMESTAMP";
        case BOSON_GETISPFRAMECOUNT:
            return "BOSON_GETISPFRAMECOUNT";
        case BOSON_WRITEUSERBADPIXELSTOALLTABLES:
            return "BOSON_WRITEUSERBADPIXELSTOALLTABLES";
        case BOSON_WRITEFACTORYBADPIXELSTOALLTABLES:
            return "BOSON_WRITEFACTORYBADPIXELSTOALLTABLES";
        case BOSON_GETTEMPDIODESTATUS:
            return "BOSON_GETTEMPDIODESTATUS";
        case BOSON_CLEARFACTORYBADPIXELSINDDR:
            return "BOSON_CLEARFACTORYBADPIXELSINDDR";
        case BOSON_GETFFCWAITOPENFRAMES:
            return "BOSON_GETFFCWAITOPENFRAMES";
        case BOSON_SETFFCWAITOPENFRAMES:
            return "BOSON_SETFFCWAITOPENFRAMES";
        case BOSON_GETFFCWAITOPENFLAGSETTLEFRAMES:
            return "BOSON_GETFFCWAITOPENFLAGSETTLEFRAMES";
        case BOSON_SETFFCWAITOPENFLAGSETTLEFRAMES:
            return "BOSON_SETFFCWAITOPENFLAGSETTLEFRAMES";
        case DVO_SETANALOGVIDEOSTATE:
            return "DVO_SETANALOGVIDEOSTATE";
        case DVO_GETANALOGVIDEOSTATE:
            return "DVO_GETANALOGVIDEOSTATE";
        case DVO_SETOUTPUTFORMAT:
            return "DVO_SETOUTPUTFORMAT";
        case DVO_GETOUTPUTFORMAT:
            return "DVO_GETOUTPUTFORMAT";
        case DVO_SETOUTPUTYCBCRSETTINGS:
            return "DVO_SETOUTPUTYCBCRSETTINGS";
        case DVO_GETOUTPUTYCBCRSETTINGS:
            return "DVO_GETOUTPUTYCBCRSETTINGS";
        case DVO_SETOUTPUTRGBSETTINGS:
            return "DVO_SETOUTPUTRGBSETTINGS";
        case DVO_GETOUTPUTRGBSETTINGS:
            return "DVO_GETOUTPUTRGBSETTINGS";
        case DVO_APPLYCUSTOMSETTINGS:
            return "DVO_APPLYCUSTOMSETTINGS";
        case DVO_SETDISPLAYMODE:
            return "DVO_SETDISPLAYMODE";
        case DVO_GETDISPLAYMODE:
            return "DVO_GETDISPLAYMODE";
        case DVO_SETTYPE:
            return "DVO_SETTYPE";
        case DVO_GETTYPE:
            return "DVO_GETTYPE";
        case DVO_SETVIDEOSTANDARD:
            return "DVO_SETVIDEOSTANDARD";
        case DVO_GETVIDEOSTANDARD:
            return "DVO_GETVIDEOSTANDARD";
        case DVO_SETCHECKVIDEODACPRESENT:
            return "DVO_SETCHECKVIDEODACPRESENT";
        case DVO_GETCHECKVIDEODACPRESENT:
            return "DVO_GETCHECKVIDEODACPRESENT";
        case DVO_SETCUSTOMLCDCONFIG:
            return "DVO_SETCUSTOMLCDCONFIG";
        case DVO_GETCUSTOMLCDCONFIG:
            return "DVO_GETCUSTOMLCDCONFIG";
        case DVO_SETLCDCONFIG:
            return "DVO_SETLCDCONFIG";
        case DVO_GETLCDCONFIG:
            return "DVO_GETLCDCONFIG";
        case DVO_GETCLOCKINFO:
            return "DVO_GETCLOCKINFO";
        case DVO_SETALLCUSTOMLCDCONFIGS:
            return "DVO_SETALLCUSTOMLCDCONFIGS";
        case DVO_GETALLCUSTOMLCDCONFIGS:
            return "DVO_GETALLCUSTOMLCDCONFIGS";
        case DVO_SETOUTPUTIR16FORMAT:
            return "DVO_SETOUTPUTIR16FORMAT";
        case DVO_GETOUTPUTIR16FORMAT:
            return "DVO_GETOUTPUTIR16FORMAT";
        case CAPTURE_SINGLEFRAME:
            return "CAPTURE_SINGLEFRAME";
        case CAPTURE_FRAMES:
            return "CAPTURE_FRAMES";
        case CAPTURE_SINGLEFRAMEWITHSRC:
            return "CAPTURE_SINGLEFRAMEWITHSRC";
        case CAPTURE_SINGLEFRAMETOFILE:
            return "CAPTURE_SINGLEFRAMETOFILE";
        case SCNR_SETENABLESTATE:
            return "SCNR_SETENABLESTATE";
        case SCNR_GETENABLESTATE:
            return "SCNR_GETENABLESTATE";
        case SCNR_SETTHCOLSUM:
            return "SCNR_SETTHCOLSUM";
        case SCNR_GETTHCOLSUM:
            return "SCNR_GETTHCOLSUM";
        case SCNR_SETTHPIXEL:
            return "SCNR_SETTHPIXEL";
        case SCNR_GETTHPIXEL:
            return "SCNR_GETTHPIXEL";
        case SCNR_SETMAXCORR:
            return "SCNR_SETMAXCORR";
        case SCNR_GETMAXCORR:
            return "SCNR_GETMAXCORR";
        case SCNR_GETTHPIXELAPPLIED:
            return "SCNR_GETTHPIXELAPPLIED";
        case SCNR_GETMAXCORRAPPLIED:
            return "SCNR_GETMAXCORRAPPLIED";
        case SCNR_SETTHCOLSUMSAFE:
            return "SCNR_SETTHCOLSUMSAFE";
        case SCNR_GETTHCOLSUMSAFE:
            return "SCNR_GETTHCOLSUMSAFE";
        case SCNR_SETTHPIXELSAFE:
            return "SCNR_SETTHPIXELSAFE";
        case SCNR_GETTHPIXELSAFE:
            return "SCNR_GETTHPIXELSAFE";
        case SCNR_SETMAXCORRSAFE:
            return "SCNR_SETMAXCORRSAFE";
        case SCNR_GETMAXCORRSAFE:
            return "SCNR_GETMAXCORRSAFE";
        case AGC_SETPERCENTPERBIN:
            return "AGC_SETPERCENTPERBIN";
        case AGC_GETPERCENTPERBIN:
            return "AGC_GETPERCENTPERBIN";
        case AGC_SETLINEARPERCENT:
            return "AGC_SETLINEARPERCENT";
        case AGC_GETLINEARPERCENT:
            return "AGC_GETLINEARPERCENT";
        case AGC_SETOUTLIERCUT:
            return "AGC_SETOUTLIERCUT";
        case AGC_GETOUTLIERCUT:
            return "AGC_GETOUTLIERCUT";
        case AGC_GETDROUT:
            return "AGC_GETDROUT";
        case AGC_SETMAXGAIN:
            return "AGC_SETMAXGAIN";
        case AGC_GETMAXGAIN:
            return "AGC_GETMAXGAIN";
        case AGC_SETDF:
            return "AGC_SETDF";
        case AGC_GETDF:
            return "AGC_GETDF";
        case AGC_SETGAMMA:
            return "AGC_SETGAMMA";
        case AGC_GETGAMMA:
            return "AGC_GETGAMMA";
        case AGC_GETFIRSTBIN:
            return "AGC_GETFIRSTBIN";
        case AGC_GETLASTBIN:
            return "AGC_GETLASTBIN";
        case AGC_SETDETAILHEADROOM:
            return "AGC_SETDETAILHEADROOM";
        case AGC_GETDETAILHEADROOM:
            return "AGC_GETDETAILHEADROOM";
        case AGC_SETD2BR:
            return "AGC_SETD2BR";
        case AGC_GETD2BR:
            return "AGC_GETD2BR";
        case AGC_SETSIGMAR:
            return "AGC_SETSIGMAR";
        case AGC_GETSIGMAR:
            return "AGC_GETSIGMAR";
        case AGC_SETUSEENTROPY:
            return "AGC_SETUSEENTROPY";
        case AGC_GETUSEENTROPY:
            return "AGC_GETUSEENTROPY";
        case AGC_SETROI:
            return "AGC_SETROI";
        case AGC_GETROI:
            return "AGC_GETROI";
        case AGC_GETMAXGAINAPPLIED:
            return "AGC_GETMAXGAINAPPLIED";
        case AGC_GETSIGMARAPPLIED:
            return "AGC_GETSIGMARAPPLIED";
        case AGC_SETOUTLIERCUTBALANCE:
            return "AGC_SETOUTLIERCUTBALANCE";
        case AGC_GETOUTLIERCUTBALANCE:
            return "AGC_GETOUTLIERCUTBALANCE";
        case AGC_GETOUTLIERCUTAPPLIED:
            return "AGC_GETOUTLIERCUTAPPLIED";
        case AGC_GETTFTHRESHOLDS:
            return "AGC_GETTFTHRESHOLDS";
        case AGC_SETTFTHRESHOLDS:
            return "AGC_SETTFTHRESHOLDS";
        case AGC_GETMODE:
            return "AGC_GETMODE";
        case AGC_SETMODE:
            return "AGC_SETMODE";
        case TF_SETENABLESTATE:
            return "TF_SETENABLESTATE";
        case TF_GETENABLESTATE:
            return "TF_GETENABLESTATE";
        case TF_SETDELTA_NF:
            return "TF_SETDELTA_NF";
        case TF_GETDELTA_NF:
            return "TF_GETDELTA_NF";
        case TF_SETTHDELTAMOTION:
            return "TF_SETTHDELTAMOTION";
        case TF_GETTHDELTAMOTION:
            return "TF_GETTHDELTAMOTION";
        case TF_SETWLUT:
            return "TF_SETWLUT";
        case TF_GETWLUT:
            return "TF_GETWLUT";
        case TF_GETMOTIONCOUNT:
            return "TF_GETMOTIONCOUNT";
        case TF_SETMOTIONTHRESHOLD:
            return "TF_SETMOTIONTHRESHOLD";
        case TF_GETMOTIONTHRESHOLD:
            return "TF_GETMOTIONTHRESHOLD";
        case TF_GETDELTA_NFAPPLIED:
            return "TF_GETDELTA_NFAPPLIED";
        case TF_GETTHDELTAMOTIONAPPLIED:
            return "TF_GETTHDELTAMOTIONAPPLIED";
        case TF_SETTEMPSIGNALCOMPFACTORLUT:
            return "TF_SETTEMPSIGNALCOMPFACTORLUT";
        case TF_GETTEMPSIGNALCOMPFACTORLUT:
            return "TF_GETTEMPSIGNALCOMPFACTORLUT";
        case TF_GETRNF:
            return "TF_GETRNF";
        case MEM_READCAPTURE:
            return "MEM_READCAPTURE";
        case MEM_GETCAPTURESIZE:
            return "MEM_GETCAPTURESIZE";
        case MEM_WRITEFLASH:
            return "MEM_WRITEFLASH";
        case MEM_READFLASH:
            return "MEM_READFLASH";
        case MEM_GETFLASHSIZE:
            return "MEM_GETFLASHSIZE";
        case MEM_ERASEFLASH:
            return "MEM_ERASEFLASH";
        case MEM_ERASEFLASHPARTIAL:
            return "MEM_ERASEFLASHPARTIAL";
        case MEM_READCURRENTGAIN:
            return "MEM_READCURRENTGAIN";
        case MEM_GETGAINSIZE:
            return "MEM_GETGAINSIZE";
        case MEM_GETCAPTURESIZESRC:
            return "MEM_GETCAPTURESIZESRC";
        case MEM_READCAPTURESRC:
            return "MEM_READCAPTURESRC";
        case COLORLUT_SETCONTROL:
            return "COLORLUT_SETCONTROL";
        case COLORLUT_GETCONTROL:
            return "COLORLUT_GETCONTROL";
        case COLORLUT_SETID:
            return "COLORLUT_SETID";
        case COLORLUT_GETID:
            return "COLORLUT_GETID";
        case COLORLUT_SETOUTLINECOLOR:
            return "COLORLUT_SETOUTLINECOLOR";
        case COLORLUT_GETOUTLINECOLOR:
            return "COLORLUT_GETOUTLINECOLOR";
        case COLORLUT_SETOUTLINEDISPLAY:
            return "COLORLUT_SETOUTLINEDISPLAY";
        case COLORLUT_GETOUTLINEDISPLAY:
            return "COLORLUT_GETOUTLINEDISPLAY";
        case SPNR_SETENABLESTATE:
            return "SPNR_SETENABLESTATE";
        case SPNR_GETENABLESTATE:
            return "SPNR_GETENABLESTATE";
        case SPNR_GETSTATE:
            return "SPNR_GETSTATE";
        case SPNR_SETFRAMEDELAY:
            return "SPNR_SETFRAMEDELAY";
        case SPNR_GETFRAMEDELAY:
            return "SPNR_GETFRAMEDELAY";
        case SPNR_GETSFAPPLIED:
            return "SPNR_GETSFAPPLIED";
        case SPNR_SETPSDKERNEL:
            return "SPNR_SETPSDKERNEL";
        case SPNR_GETPSDKERNEL:
            return "SPNR_GETPSDKERNEL";
        case SPNR_SETSFMIN:
            return "SPNR_SETSFMIN";
        case SPNR_GETSFMIN:
            return "SPNR_GETSFMIN";
        case SPNR_SETSFMAX:
            return "SPNR_SETSFMAX";
        case SPNR_GETSFMAX:
            return "SPNR_GETSFMAX";
        case SPNR_SETDFMIN:
            return "SPNR_SETDFMIN";
        case SPNR_GETDFMIN:
            return "SPNR_GETDFMIN";
        case SPNR_SETDFMAX:
            return "SPNR_SETDFMAX";
        case SPNR_GETDFMAX:
            return "SPNR_GETDFMAX";
        case SPNR_SETNORMTARGET:
            return "SPNR_SETNORMTARGET";
        case SPNR_GETNORMTARGET:
            return "SPNR_GETNORMTARGET";
        case SPNR_GETNORMTARGETAPPLIED:
            return "SPNR_GETNORMTARGETAPPLIED";
        case SPNR_SETTHPIX:
            return "SPNR_SETTHPIX";
        case SPNR_GETTHPIX:
            return "SPNR_GETTHPIX";
        case SPNR_SETTHPIXSUM:
            return "SPNR_SETTHPIXSUM";
        case SPNR_GETTHPIXSUM:
            return "SPNR_GETTHPIXSUM";
        case SPNR_SETMAXCORR:
            return "SPNR_SETMAXCORR";
        case SPNR_GETMAXCORR:
            return "SPNR_GETMAXCORR";
        case SCALER_GETMAXZOOM:
            return "SCALER_GETMAXZOOM";
        case SCALER_SETZOOM:
            return "SCALER_SETZOOM";
        case SCALER_GETZOOM:
            return "SCALER_GETZOOM";
        case SCALER_SETFRACTIONALZOOM:
            return "SCALER_SETFRACTIONALZOOM";
        case SCALER_SETINDEXZOOM:
            return "SCALER_SETINDEXZOOM";
        case SYSCTRL_SETFREEZESTATE:
            return "SYSCTRL_SETFREEZESTATE";
        case SYSCTRL_GETFREEZESTATE:
            return "SYSCTRL_GETFREEZESTATE";
        case SYSCTRL_GETCAMERAFRAMERATE:
            return "SYSCTRL_GETCAMERAFRAMERATE";
        case SYSCTRL_GETUPTIMESECS:
            return "SYSCTRL_GETUPTIMESECS";
        case TESTRAMP_SETTYPE:
            return "TESTRAMP_SETTYPE";
        case TESTRAMP_GETTYPE:
            return "TESTRAMP_GETTYPE";
        case TESTRAMP_SETSETTINGS:
            return "TESTRAMP_SETSETTINGS";
        case TESTRAMP_GETSETTINGS:
            return "TESTRAMP_GETSETTINGS";
        case TESTRAMP_SETMOTIONSTATE:
            return "TESTRAMP_SETMOTIONSTATE";
        case TESTRAMP_GETMOTIONSTATE:
            return "TESTRAMP_GETMOTIONSTATE";
        case TESTRAMP_SETINDEX:
            return "TESTRAMP_SETINDEX";
        case TESTRAMP_GETINDEX:
            return "TESTRAMP_GETINDEX";
        case TESTRAMP_GETMAXINDEX:
            return "TESTRAMP_GETMAXINDEX";
        case SYMBOLOGY_SETENABLE:
            return "SYMBOLOGY_SETENABLE";
        case SYMBOLOGY_CREATEBITMAP:
            return "SYMBOLOGY_CREATEBITMAP";
        case SYMBOLOGY_SENDDATA:
            return "SYMBOLOGY_SENDDATA";
        case SYMBOLOGY_CREATEARC:
            return "SYMBOLOGY_CREATEARC";
        case SYMBOLOGY_CREATETEXT:
            return "SYMBOLOGY_CREATETEXT";
        case SYMBOLOGY_MOVESPRITE:
            return "SYMBOLOGY_MOVESPRITE";
        case SYMBOLOGY_ADDTOGROUP:
            return "SYMBOLOGY_ADDTOGROUP";
        case SYMBOLOGY_REMOVEFROMGROUP:
            return "SYMBOLOGY_REMOVEFROMGROUP";
        case SYMBOLOGY_UPDATEANDSHOW:
            return "SYMBOLOGY_UPDATEANDSHOW";
        case SYMBOLOGY_UPDATEANDSHOWGROUP:
            return "SYMBOLOGY_UPDATEANDSHOWGROUP";
        case SYMBOLOGY_DELETE:
            return "SYMBOLOGY_DELETE";
        case SYMBOLOGY_DELETEGROUP:
            return "SYMBOLOGY_DELETEGROUP";
        case SYMBOLOGY_CREATEFILLEDRECTANGLE:
            return "SYMBOLOGY_CREATEFILLEDRECTANGLE";
        case SYMBOLOGY_CREATEOUTLINEDRECTANGLE:
            return "SYMBOLOGY_CREATEOUTLINEDRECTANGLE";
        case SYMBOLOGY_CREATEBITMAPFROMPNG:
            return "SYMBOLOGY_CREATEBITMAPFROMPNG";
        case SYMBOLOGY_CREATECOMPRESSEDBITMAP:
            return "SYMBOLOGY_CREATECOMPRESSEDBITMAP";
        case SYMBOLOGY_CREATEBITMAPFROMPNGFILE:
            return "SYMBOLOGY_CREATEBITMAPFROMPNGFILE";
        case SYMBOLOGY_CREATEBITMAPFROMFILE:
            return "SYMBOLOGY_CREATEBITMAPFROMFILE";
        case SYMBOLOGY_RESETWRITEPOSITION:
            return "SYMBOLOGY_RESETWRITEPOSITION";
        case SYMBOLOGY_MOVEBYOFFSET:
            return "SYMBOLOGY_MOVEBYOFFSET";
        case SYMBOLOGY_MOVEGROUPBYOFFSET:
            return "SYMBOLOGY_MOVEGROUPBYOFFSET";
        case SYMBOLOGY_CREATEFILLEDELLIPSE:
            return "SYMBOLOGY_CREATEFILLEDELLIPSE";
        case SYMBOLOGY_CREATELINE:
            return "SYMBOLOGY_CREATELINE";
        case SYMBOLOGY_SETZORDER:
            return "SYMBOLOGY_SETZORDER";
        case SYMBOLOGY_SAVECONFIGURATION:
            return "SYMBOLOGY_SAVECONFIGURATION";
        case SYMBOLOGY_RELOADCONFIGURATION:
            return "SYMBOLOGY_RELOADCONFIGURATION";
        case SYMBOLOGY_GETENABLE:
            return "SYMBOLOGY_GETENABLE";
        case SYMBOLOGY_SETCLONESNUMBER:
            return "SYMBOLOGY_SETCLONESNUMBER";
        case SYMBOLOGY_MOVECLONEBYOFFSET:
            return "SYMBOLOGY_MOVECLONEBYOFFSET";
        case SYMBOLOGY_MOVECLONESPRITE:
            return "SYMBOLOGY_MOVECLONESPRITE";
        case SYMBOLOGY_SETTRANSFORMATION:
            return "SYMBOLOGY_SETTRANSFORMATION";
        case SYMBOLOGY_UPDATEALLVISIBLE:
            return "SYMBOLOGY_UPDATEALLVISIBLE";
        case SYMBOLOGY_SETSIZEANDSCALINGMODE:
            return "SYMBOLOGY_SETSIZEANDSCALINGMODE";
        case SYMBOLOGY_CREATELINEHVT:
            return "SYMBOLOGY_CREATELINEHVT";
        case SYMBOLOGY_CREATETEXTHVT:
            return "SYMBOLOGY_CREATETEXTHVT";
        case SYMBOLOGY_CREATETEXTBG:
            return "SYMBOLOGY_CREATETEXTBG";
        case SYMBOLOGY_CREATESCALEDBITMAPFROMFILE:
            return "SYMBOLOGY_CREATESCALEDBITMAPFROMFILE";
        case FILEOPS_DIR:
            return "FILEOPS_DIR";
        case FILEOPS_CD:
            return "FILEOPS_CD";
        case FILEOPS_MD:
            return "FILEOPS_MD";
        case FILEOPS_FOPEN:
            return "FILEOPS_FOPEN";
        case FILEOPS_FCLOSE:
            return "FILEOPS_FCLOSE";
        case FILEOPS_FREAD:
            return "FILEOPS_FREAD";
        case FILEOPS_FWRITE:
            return "FILEOPS_FWRITE";
        case FILEOPS_FTELL:
            return "FILEOPS_FTELL";
        case FILEOPS_FSEEK:
            return "FILEOPS_FSEEK";
        case FILEOPS_FTRUNCATE:
            return "FILEOPS_FTRUNCATE";
        case FILEOPS_RMDIR:
            return "FILEOPS_RMDIR";
        case FILEOPS_RM:
            return "FILEOPS_RM";
        case FILEOPS_RENAME:
            return "FILEOPS_RENAME";
        case FILEOPS_GETFILESIZE:
            return "FILEOPS_GETFILESIZE";
        case JFFS2_MOUNT:
            return "JFFS2_MOUNT";
        case JFFS2_UNMOUNT:
            return "JFFS2_UNMOUNT";
        case JFFS2_GETSTATE:
            return "JFFS2_GETSTATE";
        case SPLASHSCREEN_SETDURATION:
            return "SPLASHSCREEN_SETDURATION";
        case SPLASHSCREEN_SETDATATYPE:
            return "SPLASHSCREEN_SETDATATYPE";
        case SPLASHSCREEN_SETBACKGROUND:
            return "SPLASHSCREEN_SETBACKGROUND";
        case SPLASHSCREEN_GETDURATION:
            return "SPLASHSCREEN_GETDURATION";
        case SPLASHSCREEN_GETDATATYPE:
            return "SPLASHSCREEN_GETDATATYPE";
        case SPLASHSCREEN_GETBACKGROUND:
            return "SPLASHSCREEN_GETBACKGROUND";
        case SYSTEMSYMBOLS_GETID:
            return "SYSTEMSYMBOLS_GETID";
        case SYSTEMSYMBOLS_SETID:
            return "SYSTEMSYMBOLS_SETID";
        case SYSTEMSYMBOLS_GETENABLE:
            return "SYSTEMSYMBOLS_GETENABLE";
        case SYSTEMSYMBOLS_SETENABLE:
            return "SYSTEMSYMBOLS_SETENABLE";
        case SFFC_GETSCALEFACTOR:
            return "SFFC_GETSCALEFACTOR";
        case SFFC_GETDELTATEMPLINEARCOEFF:
            return "SFFC_GETDELTATEMPLINEARCOEFF";
        case SFFC_SETDELTATEMPLINEARCOEFF:
            return "SFFC_SETDELTATEMPLINEARCOEFF";
        case SFFC_GETDELTATEMPOFFSETCOEFF:
            return "SFFC_GETDELTATEMPOFFSETCOEFF";
        case SFFC_SETDELTATEMPOFFSETCOEFF:
            return "SFFC_SETDELTATEMPOFFSETCOEFF";
        case SFFC_GETFPATEMPLINEARCOEFF:
            return "SFFC_GETFPATEMPLINEARCOEFF";
        case SFFC_SETFPATEMPLINEARCOEFF:
            return "SFFC_SETFPATEMPLINEARCOEFF";
        case SFFC_GETFPATEMPOFFSETCOEFF:
            return "SFFC_GETFPATEMPOFFSETCOEFF";
        case SFFC_SETFPATEMPOFFSETCOEFF:
            return "SFFC_SETFPATEMPOFFSETCOEFF";
        case SFFC_GETDELTATEMPTIMELIMITINSECS:
            return "SFFC_GETDELTATEMPTIMELIMITINSECS";
        case SFFC_SETDELTATEMPTIMELIMITINSECS:
            return "SFFC_SETDELTATEMPTIMELIMITINSECS";
        case IMAGESTATS_GETTOTALHISTPIXELSINROI:
            return "IMAGESTATS_GETTOTALHISTPIXELSINROI";
        case IMAGESTATS_GETPOPBELOWLOWTOHIGHTHRESH:
            return "IMAGESTATS_GETPOPBELOWLOWTOHIGHTHRESH";
        case IMAGESTATS_GETPOPABOVEHIGHTOLOWTHRESH:
            return "IMAGESTATS_GETPOPABOVEHIGHTOLOWTHRESH";
        case IMAGESTATS_SETROI:
            return "IMAGESTATS_SETROI";
        case IMAGESTATS_GETROI:
            return "IMAGESTATS_GETROI";
        case IMAGESTATS_GETFIRSTBIN:
            return "IMAGESTATS_GETFIRSTBIN";
        case IMAGESTATS_GETLASTBIN:
            return "IMAGESTATS_GETLASTBIN";
        case IMAGESTATS_GETMEAN:
            return "IMAGESTATS_GETMEAN";
        case IMAGESTATS_GETFIRSTBININROI:
            return "IMAGESTATS_GETFIRSTBININROI";
        case IMAGESTATS_GETLASTBININROI:
            return "IMAGESTATS_GETLASTBININROI";
        case IMAGESTATS_GETMEANINROI:
            return "IMAGESTATS_GETMEANINROI";
        case IMAGESTATS_GETIMAGESTATS:
            return "IMAGESTATS_GETIMAGESTATS";
        case SRNR_SETENABLESTATE:
            return "SRNR_SETENABLESTATE";
        case SRNR_GETENABLESTATE:
            return "SRNR_GETENABLESTATE";
        case SRNR_SETTHROWSUM:
            return "SRNR_SETTHROWSUM";
        case SRNR_GETTHROWSUM:
            return "SRNR_GETTHROWSUM";
        case SRNR_SETTHPIXEL:
            return "SRNR_SETTHPIXEL";
        case SRNR_GETTHPIXEL:
            return "SRNR_GETTHPIXEL";
        case SRNR_SETMAXCORR:
            return "SRNR_SETMAXCORR";
        case SRNR_GETMAXCORR:
            return "SRNR_GETMAXCORR";
        case SRNR_GETTHPIXELAPPLIED:
            return "SRNR_GETTHPIXELAPPLIED";
        case SRNR_GETMAXCORRAPPLIED:
            return "SRNR_GETMAXCORRAPPLIED";
        case LFSR_SETAPPLYOFFSETENABLESTATE:
            return "LFSR_SETAPPLYOFFSETENABLESTATE";
        case LFSR_GETAPPLYOFFSETENABLESTATE:
            return "LFSR_GETAPPLYOFFSETENABLESTATE";
        case SYSINFO_GETMONITORSOFTWAREREV:
            return "SYSINFO_GETMONITORSOFTWAREREV";
        case SYSINFO_GETMONITORBUILDVARIANT:
            return "SYSINFO_GETMONITORBUILDVARIANT";
        case SYSINFO_GETPRODUCTNAME:
            return "SYSINFO_GETPRODUCTNAME";
        case SYSINFO_GETCAMERASN:
            return "SYSINFO_GETCAMERASN";
        case FLASHIO_SETPROTECTIONSTATE:
            return "FLASHIO_SETPROTECTIONSTATE";
        case FLASHIO_GETPROTECTIONSTATE:
            return "FLASHIO_GETPROTECTIONSTATE";
        case DUMMY_BADCOMMAND:
            return "DUMMY_BADCOMMAND";
        default:
            return "DUMMY_BADCOMMAND";
    }
}